# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.0

# mod
mod_id=simpleintro
mod_name=SimpleIntro
mod_version=2.0.0
mod_author=["RCalosena"]
mod_description=Starting Cutscene on World Creation
mixin_loader_class=simpleintro.SimpleIntroPlugin

# dependencies
aquaacrobatics_version=321792:5225456
hwyla_version=253449:2568751
fermiumbooter_version=968474:7279112
rpghud_version=235670:3015688